### ISSUE TITLE
TypeError: strptime() argument 1 must be str, not None

### ISSUE THREAD

**Issue by fridgerator** [Parallels/rq-dashboard#140]
I get this when trying to view the dashboard.

Any ideas?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/rq_dashboard/web.py", line 138, in overview
    workers=Worker.all(),
  File "/usr/local/lib/python3.5/site-packages/rq/worker.py", line 109, in all
    for key in reported_working]
  File "/usr/local/lib/python3.5/site-packages/rq/worker.py", line 109, in <listcomp>
    for key in reported_working]
  File "/usr/local/lib/python3.5/site-packages/rq/worker.py", line 136, in find_by_key
    worker.refresh()
  File "/usr/local/lib/python3.5/site-packages/rq/worker.py", line 547, in refresh
    self.birth_date = utcparse(as_text(birth))
  File "/usr/local/lib/python3.5/site-packages/rq/utils.py", line 169, in utcparse
    return datetime.datetime.strptime(string, _TIMESTAMP_FORMAT)
TypeError: strptime() argument 1 must be str, not None
```

**Comment by fridgerator** [comment]
Seems to happen if my workers are running for more than a few days

**Comment by jfunez** [comment]
Also happen when using `rq info` command. for example:
```
rq info -u $REDIS_URL
failed       | 0
qss_collections | 0
qss_issues   | 0
qss_articles | 0
qss_press_releases | 0
qss_news     | 0
qss_journals | 0
7 queues, 0 jobs total

Traceback (most recent call last):
  File "/usr/local/bin/rq", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rq/cli/cli.py", line 73, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rq/cli/cli.py", line 162, in info
    cli_config.queue_class, cli_config.worker_class)
  File "/usr/local/lib/python2.7/site-packages/rq/cli/helpers.py", line 199, in refresh
    func(*args)
  File "/usr/local/lib/python2.7/site-packages/rq/cli/helpers.py", line 188, in show_both
    show_workers(queues, raw, by_queue, queue_class, worker_class)
  File "/usr/local/lib/python2.7/site-packages/rq/cli/helpers.py", line 153, in show_workers
    ws = worker_class.all()
  File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 109, in all
    for key in reported_working]
  File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 136, in find_by_key
    worker.refresh()
  File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 547, in refresh
    self.birth_date = utcparse(as_text(birth))
  File "/usr/local/lib/python2.7/site-packages/rq/utils.py", line 169, in utcparse
    return datetime.datetime.strptime(string, _TIMESTAMP_FORMAT)
TypeError: strptime() argument 1 must be string, not None
```

**Comment by eoranged** [comment]
Looks like a problem with rq itself.
Could you please tell which rq library version you are running?

**Comment by jfunez** [comment]
Hi @eoranged 

In my case I'm using `python 2.7.13`, `rq==0.9.1` and `rq-dashboard==0.3.10`

HTH

**Comment by fridgerator** [comment]
`python 3.5.2`, `rq==0.8.1`, `rq-dashboard==0.3.8`

**Comment by swift1911** [comment]
i have print worker hget data:

['sz-prod', 'idle', None, '2018-01-30T02:33:18.883925Z', '2018-01-15T02:39:37.466777Z', None, '28', '14261168']
['sz-prod', 'idle', None, '2018-01-30T02:32:54.940160Z', '2018-01-15T02:39:37.468729Z', None, '21', '10723135']
[None, 'idle', None, '2018-01-30T02:31:45.720040Z', None, None, '10', '5006497']


i think that birth is None

**Comment by eoranged** [comment]
It looks like issue with RQ Itself.
And I don't see this happening with recent versions.
If you stumble upon this with recent RQ versions, please reopen this.
