### ISSUE TITLE
RQ Dashboard do not work with RQ 1.0

### ISSUE THREAD

**Issue by AlexanderPashuk** [Parallels/rq-dashboard#189]
Hey there,

After RQ update from 0.13.0 to 1.0 I can't get to work Dashboard in my app. Currently I have RQ Dashboard 0.5.1. Seems like Dashboard do not provide Redis port to `rq` module.

I have the following config:

```python
class BaseConfiguration(object):
    """Class with common configuration variables"""
    # ...

    # RQ settings
    REDIS_URL = 'redis://redis:6379/0'
    RQ_POLL_INTERVAL = 2500  #: Web interface poll period for updates in ms
    WEB_BACKGROUND = "black"
    DELETE_JOBS = False
    RQ_REDIS_URL = 'redis://redis:6379/0'

    # ...
```

Full error log:
```
[Wed Jul 10 10:44:09.621389 2019] [wsgi:error] [pid 17:tid 140621855328000] /opt/app/api
[Wed Jul 10 10:44:10.173315 2019] [wsgi:error] [pid 17:tid 140621855328000] [2019-07-10 10:44:10,173] INFO in __init__: Initialized all extensions successfully...
[Wed Jul 10 10:44:10.216214 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082] mod_wsgi (pid=17): Exception occurred processing WSGI script '/opt/app/wsgi.py'.
[Wed Jul 10 10:44:10.221240 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082] Traceback (most recent call last):
[Wed Jul 10 10:44:10.221326 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 988, in get_connection
[Wed Jul 10 10:44:10.221334 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     connection = self._available_connections.pop()
[Wed Jul 10 10:44:10.221364 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082] IndexError: pop from empty list
[Wed Jul 10 10:44:10.221377 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]
[Wed Jul 10 10:44:10.221382 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082] During handling of the above exception, another exception occurred:
[Wed Jul 10 10:44:10.221387 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]
[Wed Jul 10 10:44:10.221394 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082] Traceback (most recent call last):
[Wed Jul 10 10:44:10.221454 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2463, in __call__
[Wed Jul 10 10:44:10.221460 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     return self.wsgi_app(environ, start_response)
[Wed Jul 10 10:44:10.221467 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2449, in wsgi_app
[Wed Jul 10 10:44:10.221472 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     response = self.handle_exception(e)
[Wed Jul 10 10:44:10.221480 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1866, in handle_exception
[Wed Jul 10 10:44:10.221485 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     reraise(exc_type, exc_value, tb)
[Wed Jul 10 10:44:10.221492 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
[Wed Jul 10 10:44:10.221497 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     raise value
[Wed Jul 10 10:44:10.221504 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
[Wed Jul 10 10:44:10.221509 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     response = self.full_dispatch_request()
[Wed Jul 10 10:44:10.221516 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
[Wed Jul 10 10:44:10.221530 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     rv = self.handle_user_exception(e)
[Wed Jul 10 10:44:10.221538 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
[Wed Jul 10 10:44:10.221543 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     reraise(exc_type, exc_value, tb)
[Wed Jul 10 10:44:10.221549 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
[Wed Jul 10 10:44:10.221553 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     raise value
[Wed Jul 10 10:44:10.221560 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
[Wed Jul 10 10:44:10.221564 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     rv = self.dispatch_request()
[Wed Jul 10 10:44:10.221571 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
[Wed Jul 10 10:44:10.221575 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jul 10 10:44:10.221582 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/rq_dashboard/web.py", line 162, in overview
[Wed Jul 10 10:44:10.221586 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     failed = get_failed_queue()
[Wed Jul 10 10:44:10.221593 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/rq_dashboard/compat.py", line 89, in get_failed_queue
[Wed Jul 10 10:44:10.221597 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     return FailedQueue()
[Wed Jul 10 10:44:10.221604 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/rq_dashboard/compat.py", line 22, in __init__
[Wed Jul 10 10:44:10.221608 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     self._registries = (q.failed_job_registry for q in Queue.all())
[Wed Jul 10 10:44:10.221615 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/rq/queue.py", line 41, in all
[Wed Jul 10 10:44:10.221620 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     for rq_key in connection.smembers(cls.redis_queues_keys)
[Wed Jul 10 10:44:10.221626 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 1916, in smembers
[Wed Jul 10 10:44:10.221630 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     return self.execute_command('SMEMBERS', name)
[Wed Jul 10 10:44:10.221637 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 772, in execute_command
[Wed Jul 10 10:44:10.221642 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     connection = pool.get_connection(command_name, **options)
[Wed Jul 10 10:44:10.221648 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 990, in get_connection
[Wed Jul 10 10:44:10.221652 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     connection = self.make_connection()
[Wed Jul 10 10:44:10.221659 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 1025, in make_connection
[Wed Jul 10 10:44:10.221667 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     return self.connection_class(**self.connection_kwargs)
[Wed Jul 10 10:44:10.221675 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 452, in __init__
[Wed Jul 10 10:44:10.221679 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082]     self.port = int(port)
[Wed Jul 10 10:44:10.221707 2019] [wsgi:error] [pid 17:tid 140621855328000] [remote 172.19.0.1:43082] TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

After downgrade to `rq_dashboard` 0.4.0 and `rq` 0.13.0 app works fine. 

I will be glad to hear any ideas about how to fix it. Can provide any details that can help to fix.

**Comment by eoranged** [comment]
Hello, Alexander!
The compatibility fix was in master for some time. Please update to rq_dashboard 0.5.2.
It will warn you about deprecated configuration parameter values, which are the cause of such problem.
Please let me know If It helps.

**Comment by AlexanderPashuk** [comment]
After update to 0.5.2 the issue is gone (even without changing configuration).

Thank you!
