### ISSUE TITLE
RQ-Dashboard throws "Could not unpickle', ValueError('unsupported pickle protocol: 5')" when using RQ-Scheduler

### ISSUE THREAD

**Issue by BartlomiejSkwira** [Parallels/rq-dashboard#355]
I'm using a combination of these libraries (all run under Docker):
- django-rq 2.3.2 
- rq-dashboard - docker image https://hub.docker.com/r/eoranged/rq-dashboard
- rq-scheduler 0.10.0

When I schedule a periodic job with cron like so:
```
 scheduler.cron(
            "24 12 * * *",  # A cron string (e.g. "0 0 * * 0")
            func=foo,  # Function to be queued
            args=[],  # Arguments passed into function when executed
            kwargs={},  # Keyword arguments passed into function when executed
            repeat=None,  # Repeat this number of times (None means repeat forever)
            queue_name='default',  # In which queue the job should be put in
            meta={},  # Arbitrary pickleable data on the job itself
            use_local_timezone=False  # Interpret hours in the local timezone
    )
```

The job is executed properly, but rq-dashboard throws an exception when click the finshed job. Here is a stacktrace:
```
rq_dashboard_1  | Traceback (most recent call last):
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
rq_dashboard_1  |     response = self.full_dispatch_request()
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
rq_dashboard_1  |     rv = self.handle_user_exception(e)
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
rq_dashboard_1  |     reraise(exc_type, exc_value, tb)
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
rq_dashboard_1  |     raise value
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
rq_dashboard_1  |     rv = self.dispatch_request()
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
rq_dashboard_1  |     return self.view_functions[rule.endpoint](**req.view_args)
rq_dashboard_1  |   File "/rq_dashboard/web.py", line 101, in _wrapped
rq_dashboard_1  |     result_dict = f(*args, **kwargs)
rq_dashboard_1  |   File "/rq_dashboard/web.py", line 428, in list_jobs
rq_dashboard_1  |     queue_name, registry_name, offset, per_page
rq_dashboard_1  |   File "/rq_dashboard/web.py", line 233, in get_queue_registry_jobs_count
rq_dashboard_1  |     current_queue_jobs = [queue.fetch_job(job_id) for job_id in job_ids]
rq_dashboard_1  |   File "/rq_dashboard/web.py", line 233, in <listcomp>
rq_dashboard_1  |     current_queue_jobs = [queue.fetch_job(job_id) for job_id in job_ids]
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/queue.py", line 147, in fetch_job
rq_dashboard_1  |     job = self.job_class.fetch(job_id, connection=self.connection)
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 299, in fetch
rq_dashboard_1  |     job.refresh()
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 506, in refresh
rq_dashboard_1  |     self.restore(data)
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 486, in restore
rq_dashboard_1  |     self.meta = unpickle(obj.get('meta')) if obj.get('meta') else {}
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 56, in unpickle
rq_dashboard_1  |     raise UnpickleError('Could not unpickle', pickled_string, e)
rq_dashboard_1  | rq.exceptions.UnpickleError: ('Could not unpickle', ValueError('unsupported pickle protocol: 5'))
rq_dashboard_1  | 12:37:20: Exception on /0/data/jobs/default/finished/8/1.json [GET]
rq_dashboard_1  | Traceback (most recent call last):
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 54, in unpickle
rq_dashboard_1  |     obj = loads(pickled_string)
rq_dashboard_1  | ValueError: unsupported pickle protocol: 5
rq_dashboard_1  |
rq_dashboard_1  | During handling of the above exception, another exception occurred:
rq_dashboard_1  |
rq_dashboard_1  | Traceback (most recent call last):
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
rq_dashboard_1  |     response = self.full_dispatch_request()
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
rq_dashboard_1  |     rv = self.handle_user_exception(e)
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
rq_dashboard_1  |     reraise(exc_type, exc_value, tb)
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
rq_dashboard_1  |     raise value
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
rq_dashboard_1  |     rv = self.dispatch_request()
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
rq_dashboard_1  |     return self.view_functions[rule.endpoint](**req.view_args)
rq_dashboard_1  |   File "/rq_dashboard/web.py", line 101, in _wrapped
rq_dashboard_1  |     result_dict = f(*args, **kwargs)
rq_dashboard_1  |   File "/rq_dashboard/web.py", line 428, in list_jobs
rq_dashboard_1  |     queue_name, registry_name, offset, per_page
rq_dashboard_1  |   File "/rq_dashboard/web.py", line 233, in get_queue_registry_jobs_count
rq_dashboard_1  |     current_queue_jobs = [queue.fetch_job(job_id) for job_id in job_ids]
rq_dashboard_1  |   File "/rq_dashboard/web.py", line 233, in <listcomp>
rq_dashboard_1  |     current_queue_jobs = [queue.fetch_job(job_id) for job_id in job_ids]
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/queue.py", line 147, in fetch_job
rq_dashboard_1  |     job = self.job_class.fetch(job_id, connection=self.connection)
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 299, in fetch
rq_dashboard_1  |     job.refresh()
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 506, in refresh
rq_dashboard_1  |     self.restore(data)
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 486, in restore
rq_dashboard_1  |     self.meta = unpickle(obj.get('meta')) if obj.get('meta') else {}
rq_dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 56, in unpickle
rq_dashboard_1  |     raise UnpickleError('Could not unpickle', pickled_string, e)
rq_dashboard_1  | rq.exceptions.UnpickleError: ('Could not unpickle', ValueError('unsupported pickle protocol: 5'))
```

**This happens only with jobs which were created by rq-scheduler.** When I create jobs with the regular `queue.enqueue(...)` syntax, I can click on job details without a problem.

Does anyone have an idea how to fix it?

**Comment by BartlomiejSkwira** [comment]
This issue in RQ seems related https://github.com/rq/rq/issues/1168

**Comment by eoranged** [comment]
It's better to use the same major Python version on every instance and upgrade workers first. Otherwise you may face such issues.

**Comment by BartlomiejSkwira** [comment]
@eoranged Thanks for the feedback.

My Python versions are:
- `django-rq` container is running on the main image with `python-3.8.2-slim`
- I see that `rq-dashboard` is build using `python:3.7-slim`
- `rq_scheduler` is reusing the same docker image with `python-3.8.2-slim`

So I have Python 3.7 v 3.8? The major version is the same, wonder if it's still an issue.

**Comment by ucyo** [comment]
@BartlomiejSkwira You have to change the Python container from `rq-dashboard` to `python-3.8-slim` (or `python-3.8.2-slim` if you like). That will resolve the problem.

**Comment by eoranged** [comment]
Yes, seems like It's time to take a look at this project. I was a little bit busy recently, so It got a bit orphaned.

**Comment by eoranged** [comment]
@BartlomiejSkwira please try 
```
$ docker pull eoranged/rq-dashboard:latest
$ docker run -p 9181:9181 eoranged/rq-dashboard:latest
```

It's built against master branch and Python 3.8.5, which should be able to unpickle your tasks.

**Comment by BartlomiejSkwira** [comment]
Worked, thank you @eoranged for a very quick fix!
