### ISSUE TITLE
Issue with Apache mod_wsgi and threading

### ISSUE THREAD

**Issue by glenfant** [Parallels/rq-dashboard#54]
Hi,

And thanks for this valuable tool.

As part of a bigger app, I wanted to deploy rq-dashboard through Apache/mod_wsgi, but the function `rq.connections.get_current_connection()` returns None in a - appearently - random manner. This is an example of trace of what returns this function.

```
[Tue Dec 17 15:32:22 2013] [error] <redis.client.Redis object at 0x7f172896a050>
[Tue Dec 17 15:32:22 2013] [error] None
[Tue Dec 17 15:32:22 2013] [error]  None
[Tue Dec 17 15:32:24 2013] [error] None
[Tue Dec 17 15:32:24 2013] [error] None
[Tue Dec 17 15:32:24 2013] [error]  None
[Tue Dec 17 15:32:27 2013] [error] <redis.client.Redis object at 0x7f172896a050>
[Tue Dec 17 15:32:27 2013] [error] <redis.client.Redis object at 0x7f172896a050>
[Tue Dec 17 15:32:27 2013] [error]  None
[Tue Dec 17 15:32:29 2013] [error] None
[Tue Dec 17 15:32:29 2013] [error] <redis.client.Redis object at 0x7f172896a050>
[Tue Dec 17 15:32:29 2013] [error]  None
[Tue Dec 17 15:32:31 2013] [error] None
```

Here is an example of traceback I can read in the error log :

```
Traceback (most recent call last):
  File "/home/loix-devint/loix.buildout/parts/rq-dashboard-wsgiscript/rq-dashboard.wsgi", line 57, in application
    return _application(environ, start_response)
  File "/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/loix-devint/loix.buildout/eggs/rq_dashboard-0.3.3-py2.7.egg/rq_dashboard/dashboard.py", line 100, in overview
    failed = Queue('failed')
  File "/home/loix-devint/loix.buildout/eggs/rq-0.3.12-py2.7.egg/rq/queue.py", line 48, in __init__
    self.connection = resolve_connection(connection)
  File "/home/loix-devint/loix.buildout/eggs/rq-0.3.12-py2.7.egg/rq/connections.py", line 65, in resolve_connection
    'Could not resolve a Redis connection.')
NoRedisConnectionException: Could not resolve a Redis connection.
```

This can be "fixed" only when limiting the number of threads to "1" in the Apache config part of the WSGI app.

I suspect there is an issue in the initialization part that makes the thread local stack of connections in `rq.connections._connection_stack` from `rq_dashboard.dashboard.setup_rq_connection()`

The Apache config part :

``` apache
  <VirtualHost *:80>
    ServerName rq-dashboard.tld
    ServerAdmin admin@assemblee-nationale.fr

    # Note the "threads=1"
    WSGIDaemonProcess rq-dashboard.tld user=loix-devint group=apache threads=1

    SetEnv RQ_DASHBOARD_SETTINGS /home/loix-devint/loix.buildout/etc/rq_dashboard_settings.py

    WSGIScriptAlias / /home/loix-devint/loix.buildout/parts/rq-dashboard-wsgiscript/rq-dashboard.wsgi
    <Directory /home/loix-devint/loix.buildout/parts/rq-dashboard-wsgiscript>
      WSGIProcessGroup rq-dashboard.tld
      WSGIApplicationGroup %{GLOBAL}
      Order deny,allow
      Allow from all
    </Directory>
    LogLevel debug
    ErrorLog /home/loix-devint/loix.buildout/var/log/httpd/rq-dashboard/errors.log
    CustomLog /home/loix-devint/loix.buildout/var/log/httpd/rq-dashboard/access.log common
  </VirtualHost>
```

The `/home/loix-devint/loix.buildout/etc/rq_dashboard_settings.py` file:

``` python
REDIS_URL = "redis://localhost:6379/0"
RQ_POLL_INTERVAL = 2500
```

The wsgi bootstraper file `/home/loix-devint/loix.buildout/parts/rq-dashboard-wsgiscript/rq-dashboard.wsgi`

``` python
import sys
import os

sys.path[0:0] = [
    '/home/loix-devint/loix.buildout/eggs/rq_dashboard-0.3.3-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/times-0.6.2-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/simplejson-3.3.1-py2.7-linux-x86_64.egg',
    '/home/loix-devint/loix.buildout/eggs/redis-2.8.0-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/Flask-0.10.1-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/rq-0.3.12-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/python_dateutil-2.2-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/pytz-2013.8-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/itsdangerous-0.23-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/Jinja2-2.7.1-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/Werkzeug-0.9.4-py2.7.egg',
    '/home/loix-devint/loix.buildout/eggs/six-1.4.1-py2.7.egg',
    '/usr/local/lib/python2.7/site-packages/MarkupSafe-0.18-py2.7-linux-x86_64.egg',
]

# Apache + WSGI env vars pushed to os.environ
envvars = [
    'RQ_DASHBOARD_SETTINGS',
]

_application = None
def application(environ, start_response):
    global _application
    for envvar in envvars:
        if envvar in environ:
            os.environ[envvar] = environ[envvar]
    if _application is None:
        from rq_dashboard.app import app as _application
    return _application(environ, start_response)
```

Any hint would be appreciated.

@Annakan follows this too...

**Comment by nvie** [comment]
Closing old issues.
