### ISSUE TITLE
Cant run rq-dashboard - DistributionNotFound times message

### ISSUE THREAD

**Issue by jimishjoban** [Parallels/rq-dashboard#59]
Trying to run rq-dashboard....  after successful installation... but errors out... Any idea?

$ rq-dashboard
Traceback (most recent call last):
  File "/usr/local/bin/rq-dashboard", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(**requires**)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: times

**Comment by akaRem** [comment]
@jimishjoban I have the same problem.

You may start python interpreter from project dir and paste code from example:

```
from flask import Flask
from rq_dashboard import RQDashboard


app = Flask(__name__)
RQDashboard(app)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run()
```

then your dashboard here http://127.0.0.1:5000/rq

**Comment by nvie** [comment]
Closing old issues.

**Comment by sh3kwon** [comment]
i had the same issue and upgrading setuptools did the trick for me
pip install --upgrade setuptools
