### ISSUE TITLE
Crash when lazy initialise with flask app

### ISSUE THREAD

**Issue by jeffery9876** [Parallels/rq-dashboard#62]
I was trying to integrate rq-dashboard into my flask app, with the following lines:

```
from rq_dashboard import RQDashboard
dashboard = RQDashboard()                    # crash here!!
```

then initialise the app from `create_app` function:

```
dashboard.init_app(app)
```

However, it crash immediately on creation. I believe this has been fixed with commit: https://github.com/nvie/rq-dashboard/commit/84b9cf244ca5327c3a99107d13e69b7613f73d64 

My question is, when are you going to release this piece of code that fixed 8 months ago?

```
› python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    import application
  File "/Users/jiequanli/Dropbox/Code/shopping2/application/__init__.py", line 4, in <module>
    import models
  File "/Users/jiequanli/Dropbox/Code/shopping2/application/models/__init__.py", line 2, in <module>
    from inventory import *
  File "/Users/jiequanli/Dropbox/Code/shopping2/application/models/inventory/__init__.py", line 3, in <module>
    from item import *
  File "/Users/jiequanli/Dropbox/Code/shopping2/application/models/inventory/item.py", line 6, in <module>
    from application.extensions import db
  File "/Users/jiequanli/Dropbox/Code/shopping2/application/extensions.py", line 48, in <module>
    dashboard = RQDashboard()
  File "/Users/jiequanli/Dropbox/Code/shopping2/env/lib/python2.7/site-packages/rq_dashboard/__init__.py", line 13, in __init__
    self.app.auth_handler = auth_handler
AttributeError: 'NoneType' object has no attribute 'auth_handler'
```

**Comment by nvie** [comment]
Closing old issues. If this issue still applies, feel free to re-open the ticket.
