### ISSUE TITLE
500 Error when accessing /rq route. 

### ISSUE THREAD

**Issue by lots0logs** [Parallels/rq-dashboard#67]
Does it support redis connections via unix sockets? That's the only reason I can come up with for this error? 

```
ERROR
/usr/local/lib/python2.7/dist-packages/flask/app.py: 1423
app
log_exception
2014-07-28 07:24:37,202
Msg: Exception on /rq/ [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/dist-packages/rq_dashboard/dashboard.py", line 100, in overview
failed = Queue('failed')
File "/usr/local/lib/python2.7/dist-packages/rq/queue.py", line 59, in __init__
self.connection = resolve_connection(connection)
File "/usr/local/lib/python2.7/dist-packages/rq/connections.py", line 70, in resolve_connection
raise NoRedisConnectionException('Could not resolve a Redis connection.')
NoRedisConnectionException: Could not resolve a Redis connection.
```

**Comment by nvie** [comment]
The `Queue` cannot instantiate because you didn't pass it a Redis connection. See http://python-rq.org/docs/connections/ for more details on how to instantiate queues with connections.

**Comment by lots0logs** [comment]
I'm sorry for not providing more details. I did pass it the connection. It was working previously but now does not. The only significant change was using a unix socket for my redis instance instead of tcp.

**Comment by nvie** [comment]
Can you provide your `flask/app.py` contents?

**Comment by maxscott** [comment]
Sorry if this is out of place, but I don't see anything on the suggested way to pass the redis connection to rq-dashboard. I've tried adding the host in the app.config['REDIS_HOST/URL'] to no avail. Maybe I missed some docs somewhere? Thanks

**Comment by lots0logs** [comment]
I have been running it as a separate process without any issues. I am using supervisor to handle starting them at boot and then keeping them running. By them I mean my flask app, rq-worker, and rq-dashboard. I then configured nginx to reverse proxy rq.mydomain.com to rq-dashboard. It's been running smoothly ever since. I hope it helps :smile:
